package tectech.thing.metaTileEntity.multi.structures;

public class BECGeneratorStructureDef {

    public static final String[][] BEC_GENERATOR = new String[][]{{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "       D1B1D       ",
        "      D11B11D      ",
        "     D11BBB11D     ",
        "     11B111B11     ",
        "     BBB1 1BBB     ",
        "     11B111B11     ",
        "     D11BBB11D     ",
        "      D11B11D      ",
        "       D1B1D       ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "       DABAD       ",
        "     DDDABADDD     ",
        "    DDD     DDD    ",
        "    DD       DD    ",
        "   DD         DD   ",
        "   AA         AA   ",
        "   BB         BB   ",
        "   AA         AA   ",
        "   DD         DD   ",
        "    DD       DD    ",
        "    DDD     DDD    ",
        "     DDDABADDD     ",
        "       DABAD       ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "       DABAD       ",
        "     DD     DD     ",
        "    D         D    ",
        "   D           D   ",
        "   D           D   ",
        "  D             D  ",
        "  A             A  ",
        "  B             B  ",
        "  A             A  ",
        "  D             D  ",
        "   D           D   ",
        "   D           D   ",
        "    D         D    ",
        "     DD     DD     ",
        "       DABAD       ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "       AABAA       ",
        "     AAA B AAA     ",
        "    AA   B   AA    ",
        "   AA  CCCCC  AA   ",
        "   A  C     C  A   ",
        "  AA C       C AA  ",
        "  A  C       C  A  ",
        "  BBBC       CBBB  ",
        "  A  C       C  A  ",
        "  AA C       C AA  ",
        "   A  C     C  A   ",
        "   AA  CCCCC  AA   ",
        "    AA   B   AA    ",
        "     AAA B AAA     ",
        "       AABAA       ",
        "                   ",
        "                   "
    },{
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " A               A ",
        " B               B ",
        " A               A ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   "
    },{
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " A               A ",
        " B               B ",
        " A               A ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   "
    },{
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "A                 A",
        "B                 B",
        "A                 A",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        "
    },{
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "A                 A",
        "B                 B",
        "A                 A",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        "
    },{
        "      AAABAAA      ",
        "    AAA  B  AAA    ",
        "   AA    B    AA   ",
        "  AA     B     AA  ",
        " AA    CCCCC    AA ",
        " A    C     C    A ",
        "AA   C       C   AA",
        "A   C         C   A",
        "A   C         C   A",
        "BBBBC         CBBBB",
        "A   C         C   A",
        "A   C         C   A",
        "AA   C       C   AA",
        " A    C     C    A ",
        " AA    CCCCC    AA ",
        "  AA     B     AA  ",
        "   AA    B    AA   ",
        "    AAA  B  AAA    ",
        "      AAABAAA      "
    },{
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "A                 A",
        "B                 B",
        "A                 A",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        "
    },{
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " A               A ",
        " B               B ",
        " A               A ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   "
    },{
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " A               A ",
        " B               B ",
        " A               A ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   "
    },{
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " A               A ",
        " B               B ",
        " A               A ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   "
    },{
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "  A             A  ",
        "  B             B  ",
        "  A             A  ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "       AABAA       ",
        "     AAA B AAA     ",
        "    AA   B   AA    ",
        "   AA  CCCCC  AA   ",
        "   A  C     C  A   ",
        "  AA C       C AA  ",
        "  A  C       C  A  ",
        "  BBBC       CBBB  ",
        "  A  C       C  A  ",
        "  AA C       C AA  ",
        "   A  C     C  A   ",
        "   AA  CCCCC  AA   ",
        "    AA   B   AA    ",
        "     AAA B AAA     ",
        "       AABAA       ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "  A             A  ",
        "  B             B  ",
        "  A             A  ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "   A           A   ",
        "   B           B   ",
        "   A           A   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "   A           A   ",
        "   B           B   ",
        "   A           A   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "   A           A   ",
        "   B           B   ",
        "   A           A   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "    A         A    ",
        "    B         B    ",
        "    A         A    ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "       AABAA       ",
        "      AA B AA      ",
        "     AA  B  AA     ",
        "    AA  CCC  AA    ",
        "    A  C   C  A    ",
        "    BBBC   CBBB    ",
        "    A  C   C  A    ",
        "    AA  CCC  AA    ",
        "     AA  B  AA     ",
        "      AA B AA      ",
        "       AABAA       ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "    A         A    ",
        "    B         B    ",
        "    A         A    ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "     A       A     ",
        "     B       B     ",
        "     A       A     ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "     A       A     ",
        "     B       B     ",
        "     A       A     ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "     A       A     ",
        "     B       B     ",
        "     A       A     ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "      A     A      ",
        "      B     B      ",
        "      A     A      ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "         B         ",
        "      A  C  A      ",
        "      BBC CBB      ",
        "      A  C  A      ",
        "         B         ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "      A     A      ",
        "      B     B      ",
        "      A     A      ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "       AA AA       ",
        "       B   B       ",
        "       AA AA       ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "       AA AA       ",
        "       B   B       ",
        "       AA AA       ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "       AA AA       ",
        "       B   B       ",
        "       AA AA       ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "        B B        ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "        B B        ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "        BOB        ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    }};


}
