package tectech.thing.metaTileEntity.multi.structures;

public class BECGeneratorStructureDef {

    public static final String[][] BEC_GENERATOR = new String[][]{{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "       D1B1D       ",
        "      D11B11D      ",
        "     D11BBB11D     ",
        "     11B111B11     ",
        "     BBB1 1BBB     ",
        "     11B111B11     ",
        "     D11BBB11D     ",
        "      D11B11D      ",
        "       D1B1D       ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "       DABAD       ",
        "     DDDABADDD     ",
        "    DDD     DDD    ",
        "    DD       DD    ",
        "   DD         DD   ",
        "   AA         AA   ",
        "   BB         BB   ",
        "   AA         AA   ",
        "   DD         DD   ",
        "    DD       DD    ",
        "    DDD     DDD    ",
        "     DDDABADDD     ",
        "       DABAD       ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "       DABAD       ",
        "     DD     DD     ",
        "    D         D    ",
        "   D           D   ",
        "   D           D   ",
        "  D             D  ",
        "  A             A  ",
        "  B             B  ",
        "  A             A  ",
        "  D             D  ",
        "   D           D   ",
        "   D           D   ",
        "    D         D    ",
        "     DD     DD     ",
        "       DABAD       ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "       AABAA       ",
        "     AAA B AAA     ",
        "    AA   B   AA    ",
        "   AA  CCCCC  AA   ",
        "   A  C     C  A   ",
        "  AA C       C AA  ",
        "  A  C       C  A  ",
        "  BBBC       CBBB  ",
        "  A  C       C  A  ",
        "  AA C       C AA  ",
        "   A  C     C  A   ",
        "   AA  CCCCC  AA   ",
        "    AA   B   AA    ",
        "     AAA B AAA     ",
        "       AABAA       ",
        "                   ",
        "                   "
    },{
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " A               A ",
        " B               B ",
        " A               A ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   "
    },{
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " A               A ",
        " B               B ",
        " A               A ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   "
    },{
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "A                 A",
        "B                 B",
        "A                 A",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        "
    },{
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "A                 A",
        "B                 B",
        "A                 A",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        "
    },{
        "      AAABAAA      ",
        "    AAA  B  AAA    ",
        "   AA    B    AA   ",
        "  AA     B     AA  ",
        " AA    CCCCC    AA ",
        " A    C     C    A ",
        "AA   C       C   AA",
        "A   C         C   A",
        "A   C         C   A",
        "BBBBC         CBBBB",
        "A   C         C   A",
        "A   C         C   A",
        "AA   C       C   AA",
        " A    C     C    A ",
        " AA    CCCCC    AA ",
        "  AA     B     AA  ",
        "   AA    B    AA   ",
        "    AAA  B  AAA    ",
        "      AAABAAA      "
    },{
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "A                 A",
        "B                 B",
        "A                 A",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        "
    },{
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " A               A ",
        " B               B ",
        " A               A ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   "
    },{
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " A               A ",
        " B               B ",
        " A               A ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   "
    },{
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " A               A ",
        " B               B ",
        " A               A ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   "
    },{
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "  A             A  ",
        "  B             B  ",
        "  A             A  ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "       AABAA       ",
        "     AAA B AAA     ",
        "    AA   B   AA    ",
        "   AA  CCCCC  AA   ",
        "   A  C     C  A   ",
        "  AA C       C AA  ",
        "  A  C       C  A  ",
        "  BBBC       CBBB  ",
        "  A  C       C  A  ",
        "  AA C       C AA  ",
        "   A  C     C  A   ",
        "   AA  CCCCC  AA   ",
        "    AA   B   AA    ",
        "     AAA B AAA     ",
        "       AABAA       ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "  A             A  ",
        "  B             B  ",
        "  A             A  ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "   A           A   ",
        "   B           B   ",
        "   A           A   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "   A           A   ",
        "   B           B   ",
        "   A           A   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "   A           A   ",
        "   B           B   ",
        "   A           A   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "    A         A    ",
        "    B         B    ",
        "    A         A    ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "       AABAA       ",
        "      AA B AA      ",
        "     AA  B  AA     ",
        "    AA  CCC  AA    ",
        "    A  C   C  A    ",
        "    BBBC   CBBB    ",
        "    A  C   C  A    ",
        "    AA  CCC  AA    ",
        "     AA  B  AA     ",
        "      AA B AA      ",
        "       AABAA       ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "    A         A    ",
        "    B         B    ",
        "    A         A    ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "     A       A     ",
        "     B       B     ",
        "     A       A     ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "     A       A     ",
        "     B       B     ",
        "     A       A     ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "     A       A     ",
        "     B       B     ",
        "     A       A     ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "      A     A      ",
        "      B     B      ",
        "      A     A      ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "         B         ",
        "      A  C  A      ",
        "      BBC CBB      ",
        "      A  C  A      ",
        "         B         ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "                   ",
        "      A     A      ",
        "      B     B      ",
        "      A     A      ",
        "                   ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "       AA AA       ",
        "       B   B       ",
        "       AA AA       ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "       AA AA       ",
        "       B   B       ",
        "       AA AA       ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "       AA AA       ",
        "       B   B       ",
        "       AA AA       ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "        B B        ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "        B B        ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        ABA        ",
        "        BOB        ",
        "        ABA        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    }};

    public static final String[][] BEC_CONTAINMENT_FIELD = {{
        "                   ",
        "      AABBBAA      ",
        "      BDB~BDB      ",
        "      AABBBAA      ",
        "                   "
    },{
        "      AAAAAAA      ",
        "    AA       AA    ",
        "    DB       BD    ",
        "    AA       AA    ",
        "      AAAAAAA      "
    },{
        "    AAABBBBBAAA    ",
        "   A   CCCCC   A   ",
        "   D           D   ",
        "   A   CCCCC   A   ",
        "    AAABBBBBAAA    "
    },{
        "   AABAAAAAAABAA   ",
        "  A  C       C  A  ",
        "  D             D  ",
        "  A  C       C  A  ",
        "   AABAAAAAAABAA   "
    },{
        "  AABAA     AABAA  ",
        " A  C  AAAAA  C  A ",
        " D     BDDDB     D ",
        " A  C  AAAAA  C  A ",
        "  AABAA     AABAA  "
    },{
        "  ABAA       AABA  ",
        " A C  A     A  C A ",
        " B    D     D    B ",
        " A C  A     A  C A ",
        "  ABAA       AABA  "
    },{
        " AAAA         AAAA ",
        "A    A       A    A",
        "B    D       D    B",
        "A    A       A    A",
        " AAAA         AAAA "
    },{
        " ABA           ABA ",
        "A C A         A C A",
        "D   B         B   D",
        "A C A         A C A",
        " ABA           ABA "
    },{
        " ABA           ABA ",
        "A C A         A C A",
        "E   D         D   E",
        "A C A         A C A",
        " ABA           ABA "
    },{
        " ABA           ABA ",
        "A C A         A C A",
        "D   D         D   D",
        "A C A         A C A",
        " ABA           ABA "
    },{
        " ABA           ABA ",
        "A C A         A C A",
        "E   D         D   E",
        "A C A         A C A",
        " ABA           ABA "
    },{
        " ABA           ABA ",
        "A C A         A C A",
        "D   B         B   D",
        "A C A         A C A",
        " ABA           ABA "
    },{
        " AAAA         AAAA ",
        "A    A       A    A",
        "B    D       D    B",
        "A    A       A    A",
        " AAAA         AAAA "
    },{
        "  ABAA       AABA  ",
        " A C  A     A  C A ",
        " B    D     D    B ",
        " A C  A     A  C A ",
        "  ABAA       AABA  "
    },{
        "  AABAA     AABAA  ",
        " A  C  AAAAA  C  A ",
        " D     BDDDB     D ",
        " A  C  AAAAA  C  A ",
        "  AABAA     AABAA  "
    },{
        "   AABAAAAAAABAA   ",
        "  A  C       C  A  ",
        "  D             D  ",
        "  A  C       C  A  ",
        "   AABAAAAAAABAA   "
    },{
        "    AAABBBBBAAA    ",
        "   A   CCCCC   A   ",
        "   D           D   ",
        "   A   CCCCC   A   ",
        "    AAABBBBBAAA    "
    },{
        "      AAAAAAA      ",
        "    AA       AA    ",
        "    DB       BD    ",
        "    AA       AA    ",
        "      AAAAAAA      "
    },{
        "                   ",
        "      AAAAAAA      ",
        "      BDEDEDB      ",
        "      AAAAAAA      ",
        "                   "
    }};

    public static final String[][] BEC_LIQUIFIER = {{
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "     C           C     ",
        "     C           C     ",
        "     C           C     ",
        "     C           C     ",
        "     C           C     ",
        "     C           C     ",
        "     C           C     ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       "
    },{
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "     C           C     ",
        "     C           C     ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "     C           C     ",
        "     C           C     ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       "
    },{
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "     C           C     ",
        "     C           C     ",
        "         C   C         ",
        "         C   C         ",
        "         C   C         ",
        "         C   C         ",
        "         C   C         ",
        "         C   C         ",
        "         C   C         ",
        "     C           C     ",
        "     C           C     ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       "
    },{
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "     C           C     ",
        "     C           C     ",
        "         C   C         ",
        "         C   C         ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "         C   C         ",
        "         C   C         ",
        "     C           C     ",
        "     C           C     ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       "
    },{
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "     C           C     ",
        "                       ",
        "         C   C         ",
        "                       ",
        "                       ",
        "       C       C       ",
        "       C       C       ",
        "       C       C       ",
        "                       ",
        "                       ",
        "         C   C         ",
        "                       ",
        "     C           C     ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       "
    },{
        "        AAAAAAA        ",
        "      AA       AA      ",
        "    AA           AA    ",
        "   A AAAA     AAAA A   ",
        "  A  A  AAAAAAA  A  A  ",
        "  A  C   A   A   C  A  ",
        " A       A   A       A ",
        " A      AC   CA      A ",
        "A      AA     AA      A",
        "A      C       C      A",
        "A   A             A   A",
        "A   A             A   A",
        "A   A             A   A",
        "A      C       C      A",
        "A      AA     AA      A",
        " A      AC   CA      A ",
        " A       A   A       A ",
        "  A  C   A   A   C  A  ",
        "  A  A  AAAAAAA  A  A  ",
        "   A AAAA     AAAA A   ",
        "    AA           AA    ",
        "      AA       AA      ",
        "        AAAFAAA        "
    },{
        "        BBBBBBB        ",
        "      BB       BB      ",
        "    BB           BB    ",
        "   B               B   ",
        "  B                 B  ",
        "  B  C           C  B  ",
        " B   A           A   B ",
        " B   A   C   C   A   B ",
        "B    AAA       AAA    B",
        "B   AA C       C AA   B",
        "B   A             A   B",
        "DEEEF             FEEED",
        "B   A             A   B",
        "B   AA C       C AA   B",
        "B    AAA       AAA    B",
        " B   A   C   C   A   B ",
        " B   A           A   B ",
        "  B  C           C  B  ",
        "  B                 B  ",
        "   B               B   ",
        "    BB           BB    ",
        "      BB       BB      ",
        "        BBBBBBB        "
    },{
        "        AAAAAAA        ",
        "      AA       AA      ",
        "    AA           AA    ",
        "   A AAAA     AAAA A   ",
        "  A  A  AAAAAAA  A  A  ",
        "  A  C   A   A   C  A  ",
        " A       A   A       A ",
        " A      AC   CA      A ",
        "A      AA     AA      A",
        "A      C       C      A",
        "A   A             A   A",
        "A   A             A   A",
        "A   A             A   A",
        "A      C       C      A",
        "A      AA     AA      A",
        " A      AC   CA      A ",
        " A       A   A       A ",
        "  A  C   A   A   C  A  ",
        "  A  A  AAAAAAA  A  A  ",
        "   A AAAA     AAAA A   ",
        "    AA           AA    ",
        "      AA       AA      ",
        "        AAA~AAA        "
    },{
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "     C           C     ",
        "                       ",
        "         C   C         ",
        "                       ",
        "                       ",
        "       C       C       ",
        "       C       C       ",
        "       C       C       ",
        "                       ",
        "                       ",
        "         C   C         ",
        "                       ",
        "     C           C     ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       "
    },{
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "     C           C     ",
        "     C           C     ",
        "         C   C         ",
        "         C   C         ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "         C   C         ",
        "         C   C         ",
        "     C           C     ",
        "     C           C     ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       "
    },{
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "     C           C     ",
        "     C           C     ",
        "         C   C         ",
        "         C   C         ",
        "         C   C         ",
        "         C   C         ",
        "         C   C         ",
        "         C   C         ",
        "         C   C         ",
        "     C           C     ",
        "     C           C     ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       "
    },{
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "     C           C     ",
        "     C           C     ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "     C           C     ",
        "     C           C     ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       "
    },{
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "     C           C     ",
        "     C           C     ",
        "     C           C     ",
        "     C           C     ",
        "     C           C     ",
        "     C           C     ",
        "     C           C     ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       ",
        "                       "
    }};
}
