package tectech.thing.metaTileEntity.multi.structures;

public class BECStructureDefinitions {

    // spotless:off

    //#region Generator

    public static final String[][] BEC_GENERATOR = {{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "       D1A1D       ",
        "      D11A11D      ",
        "     D11CCC11D     ",
        "     11C111C11     ",
        "     AAC1~1CAA     ",
        "     11C111C11     ",
        "     D11CCC11D     ",
        "      D11A11D      ",
        "       D1A1D       ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "       DBABD       ",
        "     DDDBABDDD     ",
        "    DDD     DDD    ",
        "    DD       DD    ",
        "   DD         DD   ",
        "   BB         BB   ",
        "   AA         AA   ",
        "   BB         BB   ",
        "   DD         DD   ",
        "    DD       DD    ",
        "    DDD     DDD    ",
        "     DDDBABDDD     ",
        "       DBABD       ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "       DBABD       ",
        "     DD     DD     ",
        "    D         D    ",
        "   D           D   ",
        "   D           D   ",
        "  D             D  ",
        "  B             B  ",
        "  A             A  ",
        "  B             B  ",
        "  D             D  ",
        "   D           D   ",
        "   D           D   ",
        "    D         D    ",
        "     DD     DD     ",
        "       DBABD       ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "       CCACC       ",
        "     CCC A CCC     ",
        "    CC   A   CC    ",
        "   CC  EEEEE  CC   ",
        "   C  E     E  C   ",
        "  CC E       E CC  ",
        "  C  E       E  C  ",
        "  AAAE       EAAA  ",
        "  C  E       E  C  ",
        "  CC E       E CC  ",
        "   C  E     E  C   ",
        "   CC  EEEEE  CC   ",
        "    CC   A   CC    ",
        "     CCC A CCC     ",
        "       CCACC       ",
        "                   ",
        "                   "
    },{
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " B               B ",
        " A               A ",
        " B               B ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   "
    },{
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " B               B ",
        " A               A ",
        " B               B ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   "
    },{
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "B                 B",
        "A                 A",
        "B                 B",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        "
    },{
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "B                 B",
        "A                 A",
        "B                 B",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        "
    },{
        "      CCCACCC      ",
        "    CCC  A  CCC    ",
        "   CC    A    CC   ",
        "  CC     A     CC  ",
        " CC    EEEEE    CC ",
        " C    E     E    C ",
        "CC   E       E   CC",
        "C   E         E   C",
        "C   E         E   C",
        "AAAAE         EAAAA",
        "C   E         E   C",
        "C   E         E   C",
        "CC   E       E   CC",
        " C    E     E    C ",
        " CC    EEEEE    CC ",
        "  CC     A     CC  ",
        "   CC    A    CC   ",
        "    CCC  A  CCC    ",
        "      CCBABCC      "
    },{
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "B                 B",
        "A                 A",
        "B                 B",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        "
    },{
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " B               B ",
        " A               A ",
        " B               B ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   "
    },{
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " B               B ",
        " A               A ",
        " B               B ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   "
    },{
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        " B               B ",
        " A               A ",
        " B               B ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   "
    },{
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "  B             B  ",
        "  A             A  ",
        "  B             B  ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "       CCACC       ",
        "     CCC A CCC     ",
        "    CC   A   CC    ",
        "   CC  EEEEE  CC   ",
        "   C  E     E  C   ",
        "  CC E       E CC  ",
        "  C  E       E  C  ",
        "  AAAE       EAAA  ",
        "  C  E       E  C  ",
        "  CC E       E CC  ",
        "   C  E     E  C   ",
        "   CC  EEEEE  CC   ",
        "    CC   A   CC    ",
        "     CCC A CCC     ",
        "       CCACC       ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "  B             B  ",
        "  A             A  ",
        "  B             B  ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "   B           B   ",
        "   A           A   ",
        "   B           B   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "   B           B   ",
        "   A           A   ",
        "   B           B   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "   B           B   ",
        "   A           A   ",
        "   B           B   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "    B         B    ",
        "    A         A    ",
        "    B         B    ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "       CCACC       ",
        "      CC A CC      ",
        "     CC  A  CC     ",
        "    CC  EEE  CC    ",
        "    C  E   E  C    ",
        "    AAAE   EAAA    ",
        "    C  E   E  C    ",
        "    CC  EEE  CC    ",
        "     CC  A  CC     ",
        "      CC A CC      ",
        "       CCACC       ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "    B         B    ",
        "    A         A    ",
        "    B         B    ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "     B       B     ",
        "     A       A     ",
        "     B       B     ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "     B       B     ",
        "     A       A     ",
        "     B       B     ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "     B       B     ",
        "     A       A     ",
        "     B       B     ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "      B     B      ",
        "      A     A      ",
        "      B     B      ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "       CCACC       ",
        "      CC A CC      ",
        "      C  E  C      ",
        "      AAE EAA      ",
        "      C  E  C      ",
        "      CC A CC      ",
        "       CCACC       ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "                   ",
        "      B     B      ",
        "      A     A      ",
        "      B     B      ",
        "                   ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "       BB BB       ",
        "       A   A       ",
        "       BB BB       ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "       BB BB       ",
        "       A   A       ",
        "       BB BB       ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "       BB BB       ",
        "       A   A       ",
        "       BB BB       ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "        A A        ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "        A A        ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    },{
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "        BAB        ",
        "        AOA        ",
        "        BAB        ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   ",
        "                   "
    }};

    //#endregion

    //#region Storage

    public static final String[][] BEC_CONTAINMENT_FIELD = {{
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                    C   C                    ",
        "                    C   C                    ",
        "                    CC1CC                    ",
        "                    C   C                    ",
        "                    C   C                    ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             "
    },{
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                   C     C                   ",
        "                  ACAAAAACA                  ",
        "                  DC EEE CD                  ",
        "                  DC E E CD                  ",
        "                  DC EEE CD                  ",
        "                  ACAAAAACA                  ",
        "                   C     C                   ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             "
    },{
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                   C     C                   ",
        "                   C     C                   ",
        "                   E     E                   ",
        "               AAAEEEEEEEEEAAA               ",
        "               DDD E     E DDD               ",
        "               DDD E     E DDD               ",
        "               DDD E     E DDD               ",
        "               AAAEEEEEEEEEAAA               ",
        "                   E     E                   ",
        "                   C     C                   ",
        "                   C     C                   ",
        "                                             ",
        "                                             ",
        "                                             "
    },{
        "                                             ",
        "                                             ",
        "                                             ",
        "                  ACAAAAACA                  ",
        "                   E     E                   ",
        "                   E     E                   ",
        "                   E     E                   ",
        "            AAAEEE         EEEAAA            ",
        "            DDD               DDD            ",
        "            DDD               DDD            ",
        "            DDD               DDD            ",
        "            AAAEEE         EEEAAA            ",
        "                   E     E                   ",
        "                   E     E                   ",
        "                   E     E                   ",
        "                  ACAAAAACA                  ",
        "                                             ",
        "                                             "
    },{
        "                                             ",
        "                                             ",
        "                   C     C                   ",
        "               AAAEEEEEEEEEAAA               ",
        "                   E     E                   ",
        "                                             ",
        "                                             ",
        "           AEEE               EEEA           ",
        "           D                     D           ",
        "           D                     D           ",
        "           D                     D           ",
        "           AEEE               EEEA           ",
        "                                             ",
        "                                             ",
        "                   E     E                   ",
        "               AAAEEEEEEEEEAAA               ",
        "                   C     C                   ",
        "                                             "
    },{
        "                                             ",
        "                                             ",
        "                   C     C                   ",
        "             AAEEE E     E EEEAA             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "         AAE                     EAA         ",
        "         DD                       DD         ",
        "         DD                       DD         ",
        "         DD                       DD         ",
        "         AAE                     EAA         ",
        "                                             ",
        "                                             ",
        "                                             ",
        "             AAEEE E     E EEEAA             ",
        "                   C     C                   ",
        "                                             "
    },{
        "                                             ",
        "                   CBBBBBC                   ",
        "                   EEEEEEE                   ",
        "           AAEE    E     E    EEAA           ",
        "                                             ",
        "                                             ",
        "                                             ",
        "        AEE                       EEA        ",
        "        D                           D        ",
        "        D                           D        ",
        "        D                           D        ",
        "        AEE                       EEA        ",
        "                                             ",
        "                                             ",
        "                                             ",
        "           AAEE    E     E    EEAA           ",
        "                   EEEEEEE                   ",
        "                   CBBBBBC                   "
    },{
        "                                             ",
        "                   C     C                   ",
        "                   E     E                   ",
        "          AEE                   EEA          ",
        "                                             ",
        "                                             ",
        "                                             ",
        "       AE                           EA       ",
        "       D                             D       ",
        "       D                             D       ",
        "       D                             D       ",
        "       AE                           EA       ",
        "                                             ",
        "                                             ",
        "                                             ",
        "          AEE                   EEA          ",
        "                   E     E                   ",
        "                   C     C                   "
    },{
        "                                             ",
        "                BBBCBBBBBCBBB                ",
        "                EEEEEEEEEEEEE                ",
        "         AE                       EA         ",
        "                                             ",
        "                                             ",
        "                                             ",
        "      AE                             EA      ",
        "      D                               D      ",
        "      D                               D      ",
        "      D                               D      ",
        "      AE                             EA      ",
        "                                             ",
        "                                             ",
        "                                             ",
        "         AE                       EA         ",
        "                EEEEEEEEEEEEE                ",
        "                BBBCBBBBBCBBB                "
    },{
        "                                             ",
        "              BB   C     C   BB              ",
        "              EE   E     E   EE              ",
        "        AE         E     E         EA        ",
        "                   E     E                   ",
        "                   EEEEEEE                   ",
        "                   E     E                   ",
        "     AE            E     E            EA     ",
        "     D             E     E             D     ",
        "     D             EEEEEEE             D     ",
        "     D             E     E             D     ",
        "     AE            E     E            EA     ",
        "                   E     E                   ",
        "                   EEEEEEE                   ",
        "                   E     E                   ",
        "        AE         E     E         EA        ",
        "              EE   E     E   EE              ",
        "              BB   C     C   BB              "
    },{
        "                                             ",
        "             B    BCBBBBBCB    B             ",
        "             E     C     C     E             ",
        "       AE          C     C          EA       ",
        "                   C     C                   ",
        "                 EECAAAAACEE                 ",
        "                   CDDDDDC                   ",
        "     AE            CDDDDDC            EA     ",
        "     D             CDDDDDC             D     ",
        "     D           EECAAAAACEE           D     ",
        "     D             CDDDDDC             D     ",
        "     AE            CDDDDDC            EA     ",
        "                   CDDDDDC                   ",
        "                 EECAAAAACEE                 ",
        "                   C     C                   ",
        "       AE          C     C          EA       ",
        "             E     C     C     E             ",
        "             B    BCBBBBBCB    B             "
    },{
        "                                             ",
        "            B   BBBA  A  ABBB   B            ",
        "            E                   E            ",
        "      AE                             EA      ",
        "                                             ",
        "               EEAA       AAEE               ",
        "                 DD       DD                 ",
        "    AE           DD       DD           EA    ",
        "    D            DD       DD            D    ",
        "    D          EEAA       AAEE          D    ",
        "    D            DD       DD            D    ",
        "    AE           DD       DD           EA    ",
        "                 DD       DD                 ",
        "               EEAA       AAEE               ",
        "                                             ",
        "      AE                             EA      ",
        "            E                   E            ",
        "            B   BBBA  A  ABBB   B            "
    },{
        "                                             ",
        "           B  BBB  A  A  A  BBB  B           ",
        "           E                     E           ",
        "      AE                             EA      ",
        "                                             ",
        "              EAA           AAE              ",
        "               DD           DD               ",
        "   AE          DD           DD          EA   ",
        "   D           DD           DD           D   ",
        "   D          EAA           AAE          D   ",
        "   D           DD           DD           D   ",
        "   AE          DD           DD          EA   ",
        "               DD           DD               ",
        "              EAA           AAE              ",
        "                                             ",
        "      AE                             EA      ",
        "           E                     E           ",
        "           B  BBB  A  A  A  BBB  B           "
    },{
        "                                             ",
        "          B  BB    A  A  A    BB  B          ",
        "          E                       E          ",
        "     AE                               EA     ",
        "                                             ",
        "             EA               AE             ",
        "              D               D              ",
        "   AE         D               D         EA   ",
        "   D          D               D          D   ",
        "   D         EA               AE         D   ",
        "   D          D               D          D   ",
        "   AE         D               D         EA   ",
        "              D               D              ",
        "             EA               AE             ",
        "                                             ",
        "     AE                               EA     ",
        "          E                       E          ",
        "          B  BB    A  A  A    BB  B          "
    },{
        "                                             ",
        "         B  BB     A  A  A     BB  B         ",
        "         E                         E         ",
        "     AE                               EA     ",
        "                                             ",
        "            EA                 AE            ",
        "             D                 D             ",
        "   AE        D                 D        EA   ",
        "   D         D                 D         D   ",
        "   D        EA                 AE        D   ",
        "   D         D                 D         D   ",
        "   AE        D                 D        EA   ",
        "             D                 D             ",
        "            EA                 AE            ",
        "                                             ",
        "     AE                               EA     ",
        "         E                         E         ",
        "         B  BB     A  A  A     BB  B         "
    },{
        "                                             ",
        "         B  B      A  A  A      B  B         ",
        "         E                         E         ",
        "    AE                                 EA    ",
        "                                             ",
        "           EA                   AE           ",
        "            D                   D            ",
        "  AE        D                   D        EA  ",
        "  D         D                   D         D  ",
        "  D        EA                   AE        D  ",
        "  D         D                   D         D  ",
        "  AE        D                   D        EA  ",
        "            D                   D            ",
        "           EA                   AE           ",
        "                                             ",
        "    AE                                 EA    ",
        "         E                         E         ",
        "         B  B      A  A  A      B  B         "
    },{
        "                                             ",
        "        B  BB      ABBBBBA      BB  B        ",
        "        E           A C A           E        ",
        "    AE              A C A              EA    ",
        "                    A C A                    ",
        "           EA       A C A       AE           ",
        "            D       A C A       D            ",
        "  AE        D       A C A       D        EA  ",
        "  D         D       A C A       D         D  ",
        "  D        EA       A C A       AE        D  ",
        "  D         D       A C A       D         D  ",
        "  AE        D       A C A       D        EA  ",
        "            D       A C A       D            ",
        "           EA       A C A       AE           ",
        "                    A C A                    ",
        "    AE              A C A              EA    ",
        "        E           A ~ A           E        ",
        "        B  BB      ABBBBBA      BB  B        "
    },{
        "                                             ",
        "        B  B      BBB A BBB      B  B        ",
        "        E                           E        ",
        "    AE                                 EA    ",
        "                                             ",
        "          EA                     AE          ",
        "           D                     D           ",
        "  AE       D                     D       EA  ",
        "  D        D                     D        D  ",
        "  D       EA                     AE       D  ",
        "  D        D                     D        D  ",
        "  AE       D                     D       EA  ",
        "           D                     D           ",
        "          EA                     AE          ",
        "                                             ",
        "    AE                                 EA    ",
        "        E                           E        ",
        "        B  B      BBB A BBB      B  B        "
    },{
        "                                             ",
        "        B BB     BB A A A BB     BB B        ",
        "        E         C       C         E        ",
        "   AE             C       C             EA   ",
        "                  C       C                  ",
        "          EA      C       C      AE          ",
        "           D      C       C      D           ",
        " AE        D      C       C      D        EA ",
        " D         D      C       C      D         D ",
        " D        EA      C       C      AE        D ",
        " D         D      C       C      D         D ",
        " AE        D      C       C      D        EA ",
        "           D      C       C      D           ",
        "          EA      C       C      AE          ",
        "                  C       C                  ",
        "   AE             C       C             EA   ",
        "        E         C       C         E        ",
        "        B BB     BB A A A BB     BB B        "
    },{
        "                                             ",
        "      CCCCCAAAAAAB  BBBBB  BAAAAAACCCCC      ",
        "    CCEEEEC          BCE          CEEEECC    ",
        "   CEEE  EC          CEC          CE  EEEC   ",
        "  CEE    EC          ECB          CE    EEC  ",
        "  CE     EC          CBC          CE     EC  ",
        " CEE     EC          BCE          CE     EEC ",
        " CE      EC          CEC          CE      EC ",
        " CE      EC          ECB          CE      EC ",
        " CE      EC          CBC          CE      EC ",
        " CE      EC          BCE          CE      EC ",
        " CE      EC          CEC          CE      EC ",
        " CEE     EC          ECB          CE     EEC ",
        "  CE     EC          CBC          CE     EC  ",
        "  CEE    EC          BCE          CE    EEC  ",
        "   CEEE  EC          CEC          CE  EEEC   ",
        "    CCEEEEC          ECB          CEEEECC    ",
        "      CCCCCAAAAAAB  BBBBB  BAAAAAACCCCC      "
    },{
        "                                             ",
        "      B B B     BBABB A BBABB     B B B      ",
        "      E E       A   C   C   A       E E      ",
        "   AE           A   B   B   A           EA   ",
        "                A   C   C   A                ",
        "         EA     A   E A E   A     AE         ",
        "          D     A   C   C   A     D          ",
        "CAE       D     A   B   B   A     D       EAC",
        "C         D     A   C   C   A     D         C",
        "C        EA     A   E A E   A     AE        C",
        "C         D     A   C   C   A     D         C",
        "CAE       D     A   B   B   A     D       EAC",
        "          D     A   C   C   A     D          ",
        "         EA     A   E A E   A     AE         ",
        "                A   C   C   A                ",
        "   AE           A   B   B   A           EA   ",
        "      E E       A   C   C   A       E E      ",
        "      B B B     BBABB A BBABB     B B B      "
    },{
        "                                             ",
        "      B B B     B  B  A  B  B     B B B      ",
        "      E E          E     B          E E      ",
        "   AE              C     C              EA   ",
        "                   B     E                   ",
        "         EA        C  A  C  D     AE         ",
        "          D        E     B  D     D          ",
        " AE       D        C     C  D     D       EA ",
        " E        D        B     E  D     D        E ",
        "1E       EA        C  A  C  D     AE       E1",
        " E        D        E     B  D     D        E ",
        " AE       D        C     C  D     D       EA ",
        "          D        B     E  D     D          ",
        "         EA        C  A  C  D     AE         ",
        "                   E     B                   ",
        "   AE              C     C              EA   ",
        "      E E          B     E          E E      ",
        "      B B B     B  B  A  B  B     B B B      "
    },{
        "                                             ",
        "      B B BAAAAABAABAAAAABAABAAAAAB B B      ",
        "      E E       C  C  A  C  C       E E      ",
        "   AE           C  E  A  E  C           EA   ",
        "                C  C  A  C  C                ",
        "         EA     C  BAAAAAB  C     AE         ",
        "          D     C  C  A  C  C     D          ",
        " AE       D     C  E  A  E  C     D       EA ",
        " E        D     C  C  A  C  C     D        E ",
        "C        EA     C  BAAAAAB  C     AE        C",
        " E        D     C  C  A  C  C     D        E ",
        " AE       D     C  E  A  E  C     D       EA ",
        "          D     C  C  A  C  C     D          ",
        "         EA     C  BAAAAAB  C     AE         ",
        "                C  C  A  C  C                ",
        "   AE           C  E  A  E  C           EA   ",
        "      E E       C  C  A  C  C       E E      ",
        "      B B BAAAAABAABAAAAABAABAAAAAB B B      "
    },{
        "                                             ",
        "      B B B     B  B  A  B  B     B B B      ",
        "      E E          B     E          E E      ",
        "   AE              C     C              EA   ",
        "                   E     B                   ",
        "         EA        C  A  C  D     AE         ",
        "          D        B     E  D     D          ",
        " AE       D        C     C  D     D       EA ",
        " E        D        E     B  D     D        E ",
        "CE       EA        C  A  C  D     AE       EC",
        " E        D        B     E  D     D        E ",
        " AE       D        C     C  D     D       EA ",
        "          D        E     B  D     D          ",
        "         EA        C  A  C  D     AE         ",
        "                   B     E                   ",
        "   AE              C     C              EA   ",
        "      E E          E     B          E E      ",
        "      B B B     B  B  A  B  B     B B B      "
    },{
        "                                             ",
        "      B B B     BBABB A BBABB     B B B      ",
        "      E E       A   C   C   A       E E      ",
        "   AE           A   B   B   A           EA   ",
        "                A   C   C   A                ",
        "         EA     A   E A E   A     AE         ",
        "          D     A   C   C   A     D          ",
        "CAE       D     A   B   B   A     D       EAC",
        "C         D     A   C   C   A     D         C",
        "C        EA     A   E A E   A     AE        C",
        "C         D     A   C   C   A     D         C",
        "CAE       D     A   B   B   A     D       EAC",
        "          D     A   C   C   A     D          ",
        "         EA     A   E A E   A     AE         ",
        "                A   C   C   A                ",
        "   AE           A   B   B   A           EA   ",
        "      E E       A   C   C   A       E E      ",
        "      B B B     BBABB A BBABB     B B B      "
    },{
        "                                             ",
        "      CCCCCAAAAAAB  BBBBB  BAAAAAACCCCC      ",
        "    CCEEEEC          ECB          CEEEECC    ",
        "   CEEE  EC          CEC          CE  EEEC   ",
        "  CEE    EC          BCE          CE    EEC  ",
        "  CE     EC          CBC          CE     EC  ",
        " CEE     EC          ECB          CE     EEC ",
        " CE      EC          CEC          CE      EC ",
        " CE      EC          BCE          CE      EC ",
        " CE      EC          CBC          CE      EC ",
        " CE      EC          ECB          CE      EC ",
        " CE      EC          CEC          CE      EC ",
        " CEE     EC          BCE          CE     EEC ",
        "  CE     EC          CBC          CE     EC  ",
        "  CEE    EC          ECB          CE    EEC  ",
        "   CEEE  EC          CEC          CE  EEEC   ",
        "    CCEEEEC          BCE          CEEEECC    ",
        "      CCCCCAAAAAAB  BBBBB  BAAAAAACCCCC      "
    },{
        "                                             ",
        "        B BB     BB A A A BB     BB B        ",
        "        E         C       C         E        ",
        "   AE             C       C             EA   ",
        "                  C       C                  ",
        "          EA      C       C      AE          ",
        "           D      C       C      D           ",
        " AE        D      C       C      D        EA ",
        " D         D      C       C      D         D ",
        " D        EA      C       C      AE        D ",
        " D         D      C       C      D         D ",
        " AE        D      C       C      D        EA ",
        "           D      C       C      D           ",
        "          EA      C       C      AE          ",
        "                  C       C                  ",
        "   AE             C       C             EA   ",
        "        E         C       C         E        ",
        "        B BB     BB A A A BB     BB B        "
    },{
        "                                             ",
        "        B  B      BBB A BBB      B  B        ",
        "        E                           E        ",
        "    AE                                 EA    ",
        "                                             ",
        "          EA                     AE          ",
        "           D                     D           ",
        "  AE       D                     D       EA  ",
        "  D        D                     D        D  ",
        "  D       EA                     AE       D  ",
        "  D        D                     D        D  ",
        "  AE       D                     D       EA  ",
        "           D                     D           ",
        "          EA                     AE          ",
        "                                             ",
        "    AE                                 EA    ",
        "        E                           E        ",
        "        B  B      BBB A BBB      B  B        "
    },{
        "                                             ",
        "        B  BB      ABBBBBA      BB  B        ",
        "        E           A C A           E        ",
        "    AE              A C A              EA    ",
        "                    A C A                    ",
        "           EA       A C A       AE           ",
        "            D       A C A       D            ",
        "  AE        D       A C A       D        EA  ",
        "  D         D       A C A       D         D  ",
        "  D        EA       A C A       AE        D  ",
        "  D         D       A C A       D         D  ",
        "  AE        D       A C A       D        EA  ",
        "            D       A C A       D            ",
        "           EA       A C A       AE           ",
        "                    A C A                    ",
        "    AE              A C A              EA    ",
        "        E           A C A           E        ",
        "        B  BB      ABBBBBA      BB  B        "
    },{
        "                                             ",
        "         B  B      A  A  A      B  B         ",
        "         E                         E         ",
        "    AE                                 EA    ",
        "                                             ",
        "           EA                   AE           ",
        "            D                   D            ",
        "  AE        D                   D        EA  ",
        "  D         D                   D         D  ",
        "  D        EA                   AE        D  ",
        "  D         D                   D         D  ",
        "  AE        D                   D        EA  ",
        "            D                   D            ",
        "           EA                   AE           ",
        "                                             ",
        "    AE                                 EA    ",
        "         E                         E         ",
        "         B  B      A  A  A      B  B         "
    },{
        "                                             ",
        "         B  BB     A  A  A     BB  B         ",
        "         E                         E         ",
        "     AE                               EA     ",
        "                                             ",
        "            EA                 AE            ",
        "             D                 D             ",
        "   AE        D                 D        EA   ",
        "   D         D                 D         D   ",
        "   D        EA                 AE        D   ",
        "   D         D                 D         D   ",
        "   AE        D                 D        EA   ",
        "             D                 D             ",
        "            EA                 AE            ",
        "                                             ",
        "     AE                               EA     ",
        "         E                         E         ",
        "         B  BB     A  A  A     BB  B         "
    },{
        "                                             ",
        "          B  BB    A  A  A    BB  B          ",
        "          E                       E          ",
        "     AE                               EA     ",
        "                                             ",
        "             EA               AE             ",
        "              D               D              ",
        "   AE         D               D         EA   ",
        "   D          D               D          D   ",
        "   D         EA               AE         D   ",
        "   D          D               D          D   ",
        "   AE         D               D         EA   ",
        "              D               D              ",
        "             EA               AE             ",
        "                                             ",
        "     AE                               EA     ",
        "          E                       E          ",
        "          B  BB    A  A  A    BB  B          "
    },{
        "                                             ",
        "           B  BBB  A  A  A  BBB  B           ",
        "           E                     E           ",
        "      AE                             EA      ",
        "                                             ",
        "              EAA           AAE              ",
        "               DD           DD               ",
        "   AE          DD           DD          EA   ",
        "   D           DD           DD           D   ",
        "   D          EAA           AAE          D   ",
        "   D           DD           DD           D   ",
        "   AE          DD           DD          EA   ",
        "               DD           DD               ",
        "              EAA           AAE              ",
        "                                             ",
        "      AE                             EA      ",
        "           E                     E           ",
        "           B  BBB  A  A  A  BBB  B           "
    },{
        "                                             ",
        "            B   BBBA  A  ABBB   B            ",
        "            E                   E            ",
        "      AE                             EA      ",
        "                                             ",
        "               EEAA       AAEE               ",
        "                 DD       DD                 ",
        "    AE           DD       DD           EA    ",
        "    D            DD       DD            D    ",
        "    D          EEAA       AAEE          D    ",
        "    D            DD       DD            D    ",
        "    AE           DD       DD           EA    ",
        "                 DD       DD                 ",
        "               EEAA       AAEE               ",
        "                                             ",
        "      AE                             EA      ",
        "            E                   E            ",
        "            B   BBBA  A  ABBB   B            "
    },{
        "                                             ",
        "             B    BCBBBBBCB    B             ",
        "             E     C     C     E             ",
        "       AE          C     C          EA       ",
        "                   C     C                   ",
        "                 EECAAAAACEE                 ",
        "                   CDDDDDC                   ",
        "     AE            CDDDDDC            EA     ",
        "     D             CDDDDDC             D     ",
        "     D           EECAAAAACEE           D     ",
        "     D             CDDDDDC             D     ",
        "     AE            CDDDDDC            EA     ",
        "                   CDDDDDC                   ",
        "                 EECAAAAACEE                 ",
        "                   C     C                   ",
        "       AE          C     C          EA       ",
        "             E     C     C     E             ",
        "             B    BCBBBBBCB    B             "
    },{
        "                                             ",
        "              BB   C     C   BB              ",
        "              EE   E     E   EE              ",
        "        AE         E     E         EA        ",
        "                   E     E                   ",
        "                   EEEEEEE                   ",
        "                   E     E                   ",
        "     AE            E     E            EA     ",
        "     D             E     E             D     ",
        "     D             EEEEEEE             D     ",
        "     D             E     E             D     ",
        "     AE            E     E            EA     ",
        "                   E     E                   ",
        "                   EEEEEEE                   ",
        "                   E     E                   ",
        "        AE         E     E         EA        ",
        "              EE   E     E   EE              ",
        "              BB   C     C   BB              "
    },{
        "                                             ",
        "                BBBCBBBBBCBBB                ",
        "                EEEEEEEEEEEEE                ",
        "         AE                       EA         ",
        "                                             ",
        "                                             ",
        "                                             ",
        "      AE                             EA      ",
        "      D                               D      ",
        "      D                               D      ",
        "      D                               D      ",
        "      AE                             EA      ",
        "                                             ",
        "                                             ",
        "                                             ",
        "         AE                       EA         ",
        "                EEEEEEEEEEEEE                ",
        "                BBBCBBBBBCBBB                "
    },{
        "                                             ",
        "                   C     C                   ",
        "                   E     E                   ",
        "          AEE                   EEA          ",
        "                                             ",
        "                                             ",
        "                                             ",
        "       AE                           EA       ",
        "       D                             D       ",
        "       D                             D       ",
        "       D                             D       ",
        "       AE                           EA       ",
        "                                             ",
        "                                             ",
        "                                             ",
        "          AEE                   EEA          ",
        "                   E     E                   ",
        "                   C     C                   "
    },{
        "                                             ",
        "                   CBBBBBC                   ",
        "                   EEEEEEE                   ",
        "           AAEE    E     E    EEAA           ",
        "                                             ",
        "                                             ",
        "                                             ",
        "        AEE                       EEA        ",
        "        D                           D        ",
        "        D                           D        ",
        "        D                           D        ",
        "        AEE                       EEA        ",
        "                                             ",
        "                                             ",
        "                                             ",
        "           AAEE    E     E    EEAA           ",
        "                   EEEEEEE                   ",
        "                   CBBBBBC                   "
    },{
        "                                             ",
        "                                             ",
        "                   C     C                   ",
        "             AAEEE E     E EEEAA             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "         AAE                     EAA         ",
        "         DD                       DD         ",
        "         DD                       DD         ",
        "         DD                       DD         ",
        "         AAE                     EAA         ",
        "                                             ",
        "                                             ",
        "                                             ",
        "             AAEEE E     E EEEAA             ",
        "                   C     C                   ",
        "                                             "
    },{
        "                                             ",
        "                                             ",
        "                   C     C                   ",
        "               AAAEEEEEEEEEAAA               ",
        "                   E     E                   ",
        "                                             ",
        "                                             ",
        "           AEEE               EEEA           ",
        "           D                     D           ",
        "           D                     D           ",
        "           D                     D           ",
        "           AEEE               EEEA           ",
        "                                             ",
        "                                             ",
        "                   E     E                   ",
        "               AAAEEEEEEEEEAAA               ",
        "                   C     C                   ",
        "                                             "
    },{
        "                                             ",
        "                                             ",
        "                                             ",
        "                  ACAAAAACA                  ",
        "                   E     E                   ",
        "                   E     E                   ",
        "                   E     E                   ",
        "            AAAEEE         EEEAAA            ",
        "            DDD               DDD            ",
        "            DDD               DDD            ",
        "            DDD               DDD            ",
        "            AAAEEE         EEEAAA            ",
        "                   E     E                   ",
        "                   E     E                   ",
        "                   E     E                   ",
        "                  ACAAAAACA                  ",
        "                                             ",
        "                                             "
    },{
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                   C     C                   ",
        "                   C     C                   ",
        "                   E     E                   ",
        "               AAAEEEEEEEEEAAA               ",
        "               DDD E     E DDD               ",
        "               DDD E     E DDD               ",
        "               DDD E     E DDD               ",
        "               AAAEEEEEEEEEAAA               ",
        "                   E     E                   ",
        "                   C     C                   ",
        "                   C     C                   ",
        "                                             ",
        "                                             ",
        "                                             "
    },{
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                   C     C                   ",
        "                  ACAAAAACA                  ",
        "                  DC EEE CD                  ",
        "                  DC E E CD                  ",
        "                  DC EEE CD                  ",
        "                  ACAAAAACA                  ",
        "                   C     C                   ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             "
    },{
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                    C   C                    ",
        "                    C   C                    ",
        "                    CC1CC                    ",
        "                    C   C                    ",
        "                    C   C                    ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             ",
        "                                             "
    }};

    //#endregion

    // spotless:on
}
